FROM debian9_ssh:stable

ARG equipo
ARG usuario
ARG proxy

ENV NOTVISIBLE "in users profile"
ENV SHELL /bin/bash
ENV TERM linux

RUN export http_proxy=${proxy} 
RUN apt-get update  
RUN apt-get update 
RUN apt-get -y upgrade 
RUN apt-get -y install python2.7 python2.7-dev python-pip python-virtualenv unixodbc unixodbc-dev python-pyodbc tdsodbc freetds-bin

COPY archivos/python2_7/etc/odbcinst.ini /etc/odbcinst.ini
